#%RAML 0.8
---
title: Twitter API
version: "1.1"
baseUri: https://api.twitter.com/{version}/
# baseUri: https://{apiDomain}.twitter.com/{version}/
# baseUriParameters:
#   apiDomain:
#     description: The sub-domain at which the API is accessible.
#     enum: [ "api" ]
securitySchemes:
  - oauth_1_0:
      description: |
        Twitter offers applications the ability to issue authenticated requests on 
        behalf of the application itself (as opposed to on behalf of a specific user). 
      type: OAuth 1.0
      settings:
        requestTokenUri: https://api.twitter.com/oauth/request_token
        authorizationUri: https://api.twitter.com/oauth/authorize
        tokenCredentialsUri: https://api.twitter.com/oauth/access_token
securedBy: [ oauth_1_0 ]
mediaType: application/json
resourceTypes:
  - base:
      uriParameters:
        mediaTypeExtension:
          enum: [ .json ]
          description: Use .json to specify application/json media type.
      get?: &common
        responses:
          200:
            description: Success!
          304:
            description: There was no new data to return.
          400:
            description: |
              The request was invalid or cannot be otherwise served. An accompanying 
              error message will explain further. In API v1.1, requests without 
              authentication are considered invalid and will yield this response.
          401:
            description: Authentication credentials were missing or incorrect.
          403:
            description: |
              The request is understood, but it has been refused or access is not 
              allowed. An accompanying error message will explain why. This code is 
              used when requests are being denied due to update limits.
          404:
            description: |
              The URI requested is invalid or the resource requested, such as a user, 
              does not exists. Also returned when the requested format is not supported 
              by the requested method.
          406:
            description: |
              Returned by the Search API when an invalid format is specified in the 
              request.
          410:
            description: |
              This resource is gone. Used to indicate that an API endpoint has been 
              turned off. For example: "The Twitter REST API v1 will soon stop 
              functioning. Please migrate to API v1.1."
          420:
            description: |
              Returned by the version 1 Search and Trends APIs when you are being rate 
              limited.
          422:
            description: |
              Returned when an image uploaded to POST account/update_profile_banner is 
              unable to be processed.
          429: 
            description: |
              Returned in API v1.1 when a request cannot be served due to the 
              application's rate limit having been exhausted for the resource. See Rate 
              Limiting in API v1.1.
          500:
            description: |
              Something is broken. Please post to the group so the Twitter team can 
              investigate.
          502:
            description: Twitter is down or being upgraded.
          503:
            description: |
              The Twitter servers are up, but overloaded with requests. Try again later.
          504:
            description: |
              The Twitter servers are up, but the request couldn't be serviced due to 
              some failure within our stack. Try again later.
      post?: *common
!include traits.yaml

# Statuses
/statuses:
  is: [ trimmable ]
  # Timelines 
  /mentions_timeline{mediaTypeExtension}:
    type: base
    is: [ nestedable ]
    get:
      description: |
        Returns the 20 most recent mentions (tweets containing a users's @screen_name) 
        for the authenticating user.
        The timeline returned is the equivalent of the one seen when you view your 
        mentions on twitter.com.
        This method can only return up to 800 tweets.
      queryParameters:
        count:
          description: |
            Specifies the number of tweets to try and retrieve, up to a maximum of 
            200. The value of count is best thought of as a limit to the number of 
            tweets to return because suspended or deleted content is removed after 
            the count has been applied. We include retweets in the count, even if 
            include_rts is not supplied. It is recommended you always send include_rts=1 
            when using this API method.
          type: integer
          maximum: 200
        since_id:
          description: |
            Returns results with an ID greater than (that is, more recent than) the 
            specified ID. There are limits to the number of Tweets which can be accessed 
            through the API. If the limit of Tweets has occured since the since_id, the 
            since_id will be forced to the oldest ID available.
          type: integer
        max_id:
          description: |
            Returns results with an ID less than (that is, older than) or equal to 
            the specified ID.
          type: integer
        contributor_details:
          description: |
            This parameter enhances the contributors element of the status response 
            to include the screen_name of the contributor. By default only the user_id 
            of the contributor is included.
          type: string
      responses:
        200:
          body:
            schema: |
              {
                  "": "http://json-schema.org/draft-03/schema",
                  "type": "object",
                  "properties": {
                      "": [
                          {
                              "properties": {
                                  "coordinates": {
                                      "properties": {
                                          "coordinates": [
                                              {
                                                  "type": "number"
                                              }
                                          ],
                                          "type": {
                                              "type": "string"
                                          }
                                      },
                                      "type": "object"
                                  },
                                  "truncated": {
                                      "type": "boolean"
                                  },
                                  "favorited": {
                                      "type": "boolean"
                                  },
                                  "created_at": {
                                      "type": "string"
                                  },
                                  "id_str": {
                                      "type": "string"
                                  },
                                  "in_reply_to_user_id_str": {
                                      "type": "string"
                                  },
                                  "entities": {
                                      "media": [
                                          {
                                              "properties": {
                                                  "id": {
                                                      "type": "integer"
                                                  },
                                                  "id_str": {
                                                      "type": "string"
                                                  },
                                                  "media_url": {
                                                      "type": "string"
                                                  },
                                                  "media_url_https": {
                                                      "type": "string"
                                                  },
                                                  "url": {
                                                      "type": "string"
                                                  },
                                                  "display_url": {
                                                      "type": "string"
                                                  },
                                                  "expanded_url": {
                                                      "type": "string"
                                                  },
                                                  "sizes": {
                                                      "large": {
                                                          "w": {
                                                              "type": "integer"
                                                          },
                                                          "resize": [
                                                              "crop",
                                                              "fit"
                                                          ],
                                                          "h": {
                                                              "type": "integer"
                                                          }
                                                      },
                                                      "medium": {
                                                          "w": {
                                                              "type": "integer"
                                                          },
                                                          "resize": [
                                                              "crop",
                                                              "fit"
                                                          ],
                                                          "h": {
                                                              "type": "integer"
                                                          }
                                                      },
                                                      "small": {
                                                          "w": {
                                                              "type": "integer"
                                                          },
                                                          "resize": [
                                                              "crop",
                                                              "fit"
                                                          ],
                                                          "h": {
                                                              "type": "integer"
                                                          }
                                                      },
                                                      "thumb": {
                                                          "w": {
                                                              "type": "integer"
                                                          },
                                                          "resize": [
                                                              "crop",
                                                              "fit"
                                                          ],
                                                          "h": {
                                                              "type": "integer"
                                                          }
                                                      }
                                                  },
                                                  "type": "array",
                                                  "indices": [
                                                      {
                                                          "type": "integer"
                                                      }
                                                  ]
                                              },
                                              "type": "object"
                                          }
                                      ],
                                      "type": "array",
                                      "urls": [
                                          {
                                              "properties": {
                                                  "url": {
                                                      "type": "string"
                                                  },
                                                  "display_url": {
                                                      "type": "string"
                                                  },
                                                  "expanded_url": {
                                                      "type": "string"
                                                  },
                                                  "indices": [
                                                      {
                                                          "type": "integer"
                                                      }
                                                  ],
                                                  "type": "array"
                                              },
                                              "type": "object"
                                          }
                                      ],
                                      "hashtags": [
                                          {
                                              "properties": {
                                                  "text": {
                                                      "type": "string"
                                                  },
                                                  "indices": [
                                                      {
                                                          "type": "integer"
                                                      }
                                                  ],
                                                  "type": "array"
                                              },
                                              "type": "object"
                                          }
                                      ],
                                      "user_mentions": [
                                          {
                                              "properties": {
                                                  "id": {
                                                      "type": "integer"
                                                  },
                                                  "id_str": {
                                                      "type": "string"
                                                  },
                                                  "screen_name": {
                                                      "type": "string"
                                                  },
                                                  "name": {
                                                      "type": "string"
                                                  },
                                                  "indices": [
                                                      {
                                                          "type": "integer"
                                                      }
                                                  ],
                                                  "type": "array"
                                              },
                                              "type": "object"
                                          }
                                      ]
                                  },
                                  "text": {
                                      "type": "string"
                                  },
                                  "contributors": [
                                      {
                                          "id": {
                                              "type": "integer"
                                          },
                                          "id_str": {
                                              "type": "string"
                                          },
                                          "screen_name": {
                                              "type": "string"
                                          }
                                      }
                                  ],
                                  "type": "array",
                                  "id": {
                                      "type": "integer"
                                  },
                                  "retweet_count": {
                                      "type": "integer"
                                  },
                                  "in_reply_to_status_id_str": {
                                      "type": "string"
                                  },
                                  "geo": {
                                      "type": "string"
                                  },
                                  "retweeted": {
                                      "type": "boolean"
                                  },
                                  "in_reply_to_user_id": {
                                      "type": "string"
                                  },
                                  "in_reply_to_screen_name": {
                                      "type": "string"
                                  },
                                  "source": {
                                      "type": "string"
                                  },
                                  "user": {
                                      "properties": {
                                          "profile_sidebar_fill_color": {
                                              "type": "string"
                                          },
                                          "profile_background_tile": {
                                              "type": "boolean"
                                          },
                                          "profile_sidebar_border_color": {
                                              "type": "string"
                                          },
                                          "name": {
                                              "type": "string"
                                          },
                                          "profile_image_url": {
                                              "type": "string"
                                          },
                                          "location": {
                                              "type": "string"
                                          },
                                          "created_at": {
                                              "type": "string"
                                          },
                                          "follow_request_sent": {
                                              "type": "boolean"
                                          },
                                          "is_translator": {
                                              "type": "boolean"
                                          },
                                          "id_str": {
                                              "type": "string"
                                          },
                                          "profile_link_color": {
                                              "type": "string"
                                          },
                                          "entities": {
                                              "media": [
                                                  {
                                                      "properties": {
                                                          "id": {
                                                              "type": "integer"
                                                          },
                                                          "id_str": {
                                                              "type": "string"
                                                          },
                                                          "media_url": {
                                                              "type": "string"
                                                          },
                                                          "media_url_https": {
                                                              "type": "string"
                                                          },
                                                          "url": {
                                                              "type": "string"
                                                          },
                                                          "display_url": {
                                                              "type": "string"
                                                          },
                                                          "expanded_url": {
                                                              "type": "string"
                                                          },
                                                          "sizes": {
                                                              "large": {
                                                                  "w": {
                                                                      "type": "integer"
                                                                  },
                                                                  "resize": [
                                                                      "crop",
                                                                      "fit"
                                                                  ],
                                                                  "h": {
                                                                      "type": "integer"
                                                                  }
                                                              },
                                                              "medium": {
                                                                  "w": {
                                                                      "type": "integer"
                                                                  },
                                                                  "resize": [
                                                                      "crop",
                                                                      "fit"
                                                                  ],
                                                                  "h": {
                                                                      "type": "integer"
                                                                  }
                                                              },
                                                              "small": {
                                                                  "w": {
                                                                      "type": "integer"
                                                                  },
                                                                  "resize": [
                                                                      "crop",
                                                                      "fit"
                                                                  ],
                                                                  "h": {
                                                                      "type": "integer"
                                                                  }
                                                              },
                                                              "thumb": {
                                                                  "w": {
                                                                      "type": "integer"
                                                                  },
                                                                  "resize": [
                                                                      "crop",
                                                                      "fit"
                                                                  ],
                                                                  "h": {
                                                                      "type": "integer"
                                                                  }
                                                              }
                                                          },
                                                          "type": "array",
                                                          "indices": [
                                                              {
                                                                  "type": "integer"
                                                              }
                                                          ]
                                                      },
                                                      "type": "object"
                                                  }
                                              ],
                                              "type": "array",
                                              "urls": [
                                                  {
                                                      "properties": {
                                                          "url": {
                                                              "type": "string"
                                                          },
                                                          "display_url": {
                                                              "type": "string"
                                                          },
                                                          "expanded_url": {
                                                              "type": "string"
                                                          },
                                                          "indices": [
                                                              {
                                                                  "type": "integer"
                                                              }
                                                          ],
                                                          "type": "array"
                                                      },
                                                      "type": "object"
                                                  }
                                              ],
                                              "hashtags": [
                                                  {
                                                      "properties": {
                                                          "text": {
                                                              "type": "string"
                                                          },
                                                          "indices": [
                                                              {
                                                                  "type": "integer"
                                                              }
                                                          ],
                                                          "type": "array"
                                                      },
                                                      "type": "object"
                                                  }
                                              ],
                                              "user_mentions": [
                                                  {
                                                      "properties": {
                                                          "id": {
                                                              "type": "integer"
                                                          },
                                                          "id_str": {
                                                              "type": "string"
                                                          },
                                                          "screen_name": {
                                                              "type": "string"
                                                          },
                                                          "name": {
                                                              "type": "string"
                                                          },
                                                          "indices": [
                                                              {
                                                                  "type": "integer"
                                                              }
                                                          ],
                                                          "type": "array"
                                                      },
                                                      "type": "object"
                                                  }
                                              ]
                                          },
                                          "favourites_count": {
                                              "type": "integer"
                                          },
                                          "url": {
                                              "type": "string"
                                          },
                                          "default_profile": {
                                              "type": "boolean"
                                          },
                                          "contributors_enabled": {
                                              "type": "boolean"
                                          },
                                          "profile_image_url_https": {
                                              "type": "string"
                                          },
                                          "utc_offset": {
                                              "type": "integer"
                                          },
                                          "id": {
                                              "type": "integer"
                                          },
                                          "listed_count": {
                                              "type": "integer"
                                          },
                                          "profile_use_background_image": {
                                              "type": "boolean"
                                          },
                                          "followers_count": {
                                              "type": "integer"
                                          },
                                          "protected": {
                                              "type": "boolean"
                                          },
                                          "profile_text_color": {
                                              "type": "string"
                                          },
                                          "lang": {
                                              "type": "string"
                                          },
                                          "profile_background_color": {
                                              "type": "string"
                                          },
                                          "time_zone": {
                                              "type": "string"
                                          },
                                          "verified": {
                                              "type": "boolean"
                                          },
                                          "profile_background_image_url_https": {
                                              "type": "string"
                                          },
                                          "description": {
                                              "type": "string"
                                          },
                                          "geo_enabled": {
                                              "type": "boolean"
                                          },
                                          "notifications": {
                                              "type": "boolean"
                                          },
                                          "default_profile_image": {
                                              "type": "boolean"
                                          },
                                          "friends_count": {
                                              "type": "integer"
                                          },
                                          "profile_background_image_url": {
                                              "type": "string"
                                          },
                                          "statuses_count": {
                                              "type": "integer"
                                          },
                                          "following": {
                                              "type": "boolean"
                                          },
                                          "screen_name": {
                                              "type": "string"
                                          },
                                          "show_all_inline_media": {
                                              "type": "boolean"
                                          }
                                      },
                                      "type": "object"
                                  },
                                  "place": {
                                      "name": {
                                          "type": "string"
                                      },
                                      "country_code": {
                                          "type": "string"
                                      },
                                      "country": {
                                          "type": "string"
                                      },
                                      "attributes": {
                                          "properties": {
                                              "street_address": {
                                                  "type": "string"
                                              },
                                              "623:id": {
                                                  "type": "string"
                                              },
                                              "twitter": {
                                                  "type": "string"
                                              }
                                          },
                                          "type": "object"
                                      },
                                      "url": {
                                          "type": "string"
                                      },
                                      "id": {
                                          "type": "string"
                                      },
                                      "bounding_box": {
                                          "properties": {
                                              "coordinates": [
                                                  [
                                                      {
                                                          "properties": {
                                                              "": [
                                                                  {
                                                                      "type": "number"
                                                                  }
                                                              ]
                                                          },
                                                          "type": "object"
                                                      }
                                                  ]
                                              ],
                                              "type": {
                                                  "type": "string"
                                              }
                                          },
                                          "type": "object"
                                      },
                                      "full_name": {
                                          "type": "string"
                                      },
                                      "place_type": {
                                          "type": "string"
                                      }
                                  },
                                  "in_reply_to_status_id": {
                                      "type": "string"
                                  }
                              },
                              "type": "object"
                          }
                      ]
                  }
              }
            example: |
              [
                  {
                      "coordinates": null,
                      "favorited": false,
                      "truncated": false,
                      "created_at": "Mon Sep 03 13:24:14 +0000 2012",
                      "id_str": "242613977966850048",
                      "entities": {
                          "urls": [],
                          "hashtags": [],
                          "user_mentions": [
                              {
                                  "name": "Jason Costa",
                                  "id_str": "14927800",
                                  "id": 14927800,
                                  "indices": [
                                      0,
                                      11
                                  ],
                                  "screen_name": "jasoncosta"
                              },
                              {
                                  "name": "Matt Harris",
                                  "id_str": "777925",
                                  "id": 777925,
                                  "indices": [
                                      12,
                                      26
                                  ],
                                  "screen_name": "themattharris"
                              },
                              {
                                  "name": "ThinkWall",
                                  "id_str": "117426578",
                                  "id": 117426578,
                                  "indices": [
                                      109,
                                      119
                                  ],
                                  "screen_name": "thinkwall"
                              }
                          ]
                      },
                      "in_reply_to_user_id_str": "14927800",
                      "contributors": null,
                      "text": "@jasoncosta @themattharris Hey! Going to be in Frisco in October. Was hoping to have a meeting to talk about @thinkwall if you're around?",
                      "retweet_count": 0,
                      "in_reply_to_status_id_str": null,
                      "id": 242613977966850050,
                      "geo": null,
                      "retweeted": false,
                      "in_reply_to_user_id": 14927800,
                      "place": null,
                      "user": {
                          "profile_sidebar_fill_color": "EEEEEE",
                          "profile_sidebar_border_color": "000000",
                          "profile_background_tile": false,
                          "name": "Andrew Spode Miller",
                          "profile_image_url": "http://a0.twimg.com/profile_images/1227466231/spode-balloon-medium_normal.jpg",
                          "created_at": "Mon Sep 22 13:12:01 +0000 2008",
                          "location": "London via Gravesend",
                          "follow_request_sent": false,
                          "profile_link_color": "F31B52",
                          "is_translator": false,
                          "id_str": "16402947",
                          "entities": {
                              "url": {
                                  "urls": [
                                      {
                                          "expanded_url": null,
                                          "url": "http://www.linkedin.com/in/spode",
                                          "indices": [
                                              0,
                                              32
                                          ]
                                      }
                                  ]
                              },
                              "description": {
                                  "urls": []
                              }
                          },
                          "default_profile": false,
                          "contributors_enabled": false,
                          "favourites_count": 16,
                          "url": "http://www.linkedin.com/in/spode",
                          "profile_image_url_https": "https://si0.twimg.com/profile_images/1227466231/spode-balloon-medium_normal.jpg",
                          "utc_offset": 0,
                          "id": 16402947,
                          "profile_use_background_image": false,
                          "listed_count": 129,
                          "profile_text_color": "262626",
                          "lang": "en",
                          "followers_count": 2013,
                          "protected": false,
                          "notifications": null,
                          "profile_background_image_url_https": "https://si0.twimg.com/profile_background_images/16420220/twitter-background-final.png",
                          "profile_background_color": "FFFFFF",
                          "verified": false,
                          "geo_enabled": true,
                          "time_zone": "London",
                          "description": "Co-Founder/Dev (PHP/jQuery) @justFDI. Run @thinkbikes and @thinkwall for events. Ex tech journo, helps run @uktjpr. Passion for Linux and customises everything.",
                          "default_profile_image": false,
                          "profile_background_image_url": "http://a0.twimg.com/profile_background_images/16420220/twitter-background-final.png",
                          "statuses_count": 11550,
                          "friends_count": 770,
                          "following": null,
                          "show_all_inline_media": true,
                          "screen_name": "spode"
                      },
                      "in_reply_to_screen_name": "jasoncosta",
                      "source": "<a href=\"http://www.journotwit.com\" rel=\"nofollow\">JournoTwit</a>",
                      "in_reply_to_status_id": null
                  },
                  {
                      "coordinates": {
                          "coordinates": [
                              121.0132101,
                              14.5191613
                          ],
                          "type": "Point"
                      },
                      "favorited": false,
                      "truncated": false,
                      "created_at": "Mon Sep 03 08:08:02 +0000 2012",
                      "id_str": "242534402280783873",
                      "entities": {
                          "urls": [],
                          "hashtags": [
                              {
                                  "text": "twitter",
                                  "indices": [
                                      49,
                                      57
                                  ]
                              }
                          ],
                          "user_mentions": [
                              {
                                  "name": "Jason Costa",
                                  "id_str": "14927800",
                                  "id": 14927800,
                                  "indices": [
                                      14,
                                      25
                                  ],
                                  "screen_name": "jasoncosta"
                              }
                          ]
                      },
                      "in_reply_to_user_id_str": null,
                      "contributors": null,
                      "text": "Got the shirt @jasoncosta thanks man! Loving the #twitter bird on the shirt :-)",
                      "retweet_count": 0,
                      "in_reply_to_status_id_str": null,
                      "id": 242534402280783870,
                      "geo": {
                          "coordinates": [
                              14.5191613,
                              121.0132101
                          ],
                          "type": "Point"
                      },
                      "retweeted": false,
                      "in_reply_to_user_id": null,
                      "place": null,
                      "user": {
                          "profile_sidebar_fill_color": "EFEFEF",
                          "profile_sidebar_border_color": "EEEEEE",
                          "profile_background_tile": true,
                          "name": "Mikey",
                          "profile_image_url": "http://a0.twimg.com/profile_images/1305509670/chatMikeTwitter_normal.png",
                          "created_at": "Fri Jun 20 15:57:08 +0000 2008",
                          "location": "Singapore",
                          "follow_request_sent": false,
                          "profile_link_color": "009999",
                          "is_translator": false,
                          "id_str": "15181205",
                          "entities": {
                              "url": {
                                  "urls": [
                                      {
                                          "expanded_url": null,
                                          "url": "http://about.me/michaelangelo",
                                          "indices": [
                                              0,
                                              29
                                          ]
                                      }
                                  ]
                              },
                              "description": {
                                  "urls": []
                              }
                          },
                          "default_profile": false,
                          "contributors_enabled": false,
                          "favourites_count": 11,
                          "url": "http://about.me/michaelangelo",
                          "profile_image_url_https": "https://si0.twimg.com/profile_images/1305509670/chatMikeTwitter_normal.png",
                          "utc_offset": 28800,
                          "id": 15181205,
                          "profile_use_background_image": true,
                          "listed_count": 61,
                          "profile_text_color": "333333",
                          "lang": "en",
                          "followers_count": 577,
                          "protected": false,
                          "notifications": null,
                          "profile_background_image_url_https": "https://si0.twimg.com/images/themes/theme14/bg.gif",
                          "profile_background_color": "131516",
                          "verified": false,
                          "geo_enabled": true,
                          "time_zone": "Hong Kong",
                          "description": "Android Applications Developer,  Studying Martial Arts, Plays MTG, Food and movie junkie",
                          "default_profile_image": false,
                          "profile_background_image_url": "http://a0.twimg.com/images/themes/theme14/bg.gif",
                          "statuses_count": 11327,
                          "friends_count": 138,
                          "following": null,
                          "show_all_inline_media": true,
                          "screen_name": "mikedroid"
                      },
                      "in_reply_to_screen_name": null,
                      "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
                      "in_reply_to_status_id": null
                  }
              ]
